// ═══════════════════════════════════════════════════════════════════════════
// IArtcane — core/taxonomie.js : GÉNÉRÉ par infra/build-site-data.py.
// ⚠️ NE PAS ÉDITER — source unique : prompts/taxonomie.json (D-041).
// Rejouer `python infra/build-site-data.py` après toute modif de la taxonomie.
// ═══════════════════════════════════════════════════════════════════════════

/** Formes canoniques d'affichage, dans l'ordre de référence (D-022). */
export const CATS_CANON = [
  "Tableau",
  "Gravure / estampe",
  "Dessin",
  "Photographie",
  "Sculpture",
  "Céramique",
  "Verrerie",
  "Mobilier",
  "Montre / horlogerie",
  "Bijou",
  "Argenterie / métal",
  "Luminaire",
  "Textile / tapisserie",
  "Livre / document",
  "Monnaie / médaille",
  "Instrument",
  "Jouet",
  "Curiosité",
  "Art asiatique",
  "Art tribal",
  "Autre"
];

/** Variante normalisée (minuscules, sans accents, singulier) → forme canonique. */
export const VARIANTES = {
  "tableau": "Tableau",
  "peinture": "Tableau",
  "toile": "Tableau",
  "gravure": "Gravure / estampe",
  "estampe": "Gravure / estampe",
  "print": "Gravure / estampe",
  "dessin": "Dessin",
  "croquis": "Dessin",
  "photographie": "Photographie",
  "photo": "Photographie",
  "sculpture": "Sculpture",
  "statue": "Sculpture",
  "buste": "Sculpture",
  "bas-relief": "Sculpture",
  "ceramique": "Céramique",
  "poterie": "Céramique",
  "verrerie": "Verrerie",
  "verre": "Verrerie",
  "mobilier": "Mobilier",
  "meuble": "Mobilier",
  "montre": "Montre / horlogerie",
  "horlogerie": "Montre / horlogerie",
  "horloge": "Montre / horlogerie",
  "pendule": "Montre / horlogerie",
  "bijou": "Bijou",
  "joaillerie": "Bijou",
  "argenterie": "Argenterie / métal",
  "metal": "Argenterie / métal",
  "orfevrerie": "Argenterie / métal",
  "luminaire": "Luminaire",
  "lampe": "Luminaire",
  "lustre": "Luminaire",
  "textile": "Textile / tapisserie",
  "tapisserie": "Textile / tapisserie",
  "tissu": "Textile / tapisserie",
  "livre": "Livre / document",
  "document": "Livre / document",
  "manuscrit": "Livre / document",
  "monnaie": "Monnaie / médaille",
  "medaille": "Monnaie / médaille",
  "numismatique": "Monnaie / médaille",
  "instrument": "Instrument",
  "jouet": "Jouet",
  "jeu": "Jouet",
  "curiosite": "Curiosité",
  "objet de vitrine": "Curiosité",
  "curio": "Curiosité",
  "art asiatique": "Art asiatique",
  "asie": "Art asiatique",
  "extreme-orient": "Art asiatique",
  "art tribal": "Art tribal",
  "art premier": "Art tribal",
  "ethnographique": "Art tribal",
  "autre": "Autre",
  "divers": "Autre",
  "non identifie": "Autre"
};

/** Niveau 2 (D-045) : catégorie canonique → sous-catégories (technique/matière). */
export const SOUS = {
  "Tableau": [
    "Huile",
    "Aquarelle",
    "Acrylique",
    "Gouache",
    "Pastel",
    "Fusain",
    "Tempera",
    "Technique mixte",
    "Autre"
  ],
  "Gravure / estampe": [
    "Eau-forte",
    "Lithographie",
    "Sérigraphie",
    "Burin",
    "Aquatinte",
    "Xylographie",
    "Héliogravure",
    "Autre"
  ],
  "Dessin": [
    "Crayon / graphite",
    "Encre",
    "Sanguine",
    "Lavis",
    "Autre"
  ],
  "Photographie": [
    "Tirage argentique",
    "Daguerréotype / ferrotype",
    "Photo ancienne",
    "Polaroid",
    "Autre"
  ],
  "Sculpture": [
    "Bronze",
    "Marbre",
    "Terre cuite",
    "Bois",
    "Plâtre",
    "Résine",
    "Pierre",
    "Autre"
  ],
  "Céramique": [
    "Porcelaine",
    "Faïence",
    "Grès",
    "Terre cuite",
    "Émaux / émail",
    "Barbotine",
    "Autre"
  ],
  "Verrerie": [
    "Cristal",
    "Opaline",
    "Verre soufflé",
    "Verre pressé",
    "Pâte de verre",
    "Autre"
  ],
  "Mobilier": [
    "Siège",
    "Table",
    "Commode",
    "Armoire / buffet",
    "Secrétaire / bureau",
    "Lit",
    "Miroir / psyché",
    "Autre"
  ],
  "Montre / horlogerie": [
    "Montre bracelet",
    "Montre gousset",
    "Pendule",
    "Horloge de table / cartel",
    "Comtoise",
    "Réveil",
    "Autre"
  ],
  "Bijou": [
    "Bague",
    "Collier",
    "Broche",
    "Bracelet",
    "Boucles d'oreilles",
    "Parure",
    "Autre"
  ],
  "Argenterie / métal": [
    "Argent massif",
    "Métal argenté",
    "Étain",
    "Cuivre / laiton",
    "Fer forgé",
    "Bronze d'art (objet)",
    "Autre"
  ],
  "Luminaire": [
    "Lampe",
    "Lustre",
    "Applique",
    "Bougeoir / chandelier",
    "Lanterne",
    "Autre"
  ],
  "Textile / tapisserie": [
    "Tapisserie",
    "Tapis",
    "Broderie",
    "Dentelle",
    "Costume / tissu",
    "Autre"
  ],
  "Livre / document": [
    "Livre ancien",
    "Manuscrit",
    "Autographe",
    "Carte",
    "Affiche",
    "Autre"
  ],
  "Monnaie / médaille": [
    "Monnaie / pièce",
    "Médaille",
    "Jeton",
    "Décoration",
    "Autre"
  ],
  "Instrument": [
    "Musique — cordes",
    "Musique — vent",
    "Musique — clavier",
    "Scientifique / optique",
    "Autre"
  ],
  "Jouet": [
    "Poupée",
    "Train / voiture",
    "Jeu",
    "Ours / peluche",
    "Figurine / automate",
    "Autre"
  ],
  "Curiosité": [
    "Taxidermie / naturalia",
    "Minéral / fossile",
    "Objet de cabinet ⚠️ CITES",
    "Autre"
  ],
  "Art asiatique": [
    "Chine",
    "Japon",
    "Corée",
    "Inde / Asie du Sud-Est",
    "Autre"
  ],
  "Art tribal": [
    "Afrique",
    "Océanie",
    "Amérindien / précolombien",
    "Autre"
  ],
  "Autre": [
    "Autre / à identifier"
  ]
};

/** Variante de sous-catégorie → forme canonique. Clé : « <catégorie>|<variante> ». */
export const VARIANTES_SOUS = {
  "Tableau|huile": "Huile",
  "Tableau|huile sur toile": "Huile",
  "Tableau|aquarelle": "Aquarelle",
  "Tableau|acrylique": "Acrylique",
  "Tableau|gouache": "Gouache",
  "Tableau|pastel": "Pastel",
  "Tableau|fusain": "Fusain",
  "Tableau|tempera": "Tempera",
  "Tableau|technique mixte": "Technique mixte",
  "Tableau|mixte": "Technique mixte",
  "Tableau|autre": "Autre",
  "Gravure / estampe|eau-forte": "Eau-forte",
  "Gravure / estampe|eau forte": "Eau-forte",
  "Gravure / estampe|lithographie": "Lithographie",
  "Gravure / estampe|litho": "Lithographie",
  "Gravure / estampe|serigraphie": "Sérigraphie",
  "Gravure / estampe|burin": "Burin",
  "Gravure / estampe|aquatinte": "Aquatinte",
  "Gravure / estampe|xylographie": "Xylographie",
  "Gravure / estampe|bois grave": "Xylographie",
  "Gravure / estampe|heliogravure": "Héliogravure",
  "Gravure / estampe|autre": "Autre",
  "Dessin|crayon": "Crayon / graphite",
  "Dessin|graphite": "Crayon / graphite",
  "Dessin|encre": "Encre",
  "Dessin|sanguine": "Sanguine",
  "Dessin|lavis": "Lavis",
  "Dessin|autre": "Autre",
  "Photographie|tirage argentique": "Tirage argentique",
  "Photographie|argentique": "Tirage argentique",
  "Photographie|daguerreotype": "Daguerréotype / ferrotype",
  "Photographie|ferrotype": "Daguerréotype / ferrotype",
  "Photographie|ambrotype": "Daguerréotype / ferrotype",
  "Photographie|photo ancienne": "Photo ancienne",
  "Photographie|tirage ancien": "Photo ancienne",
  "Photographie|polaroid": "Polaroid",
  "Photographie|autre": "Autre",
  "Sculpture|bronze": "Bronze",
  "Sculpture|marbre": "Marbre",
  "Sculpture|terre cuite": "Terre cuite",
  "Sculpture|bois sculpte": "Bois",
  "Sculpture|bois": "Bois",
  "Sculpture|platre": "Plâtre",
  "Sculpture|resine": "Résine",
  "Sculpture|pierre": "Pierre",
  "Sculpture|autre": "Autre",
  "Céramique|porcelaine": "Porcelaine",
  "Céramique|faience": "Faïence",
  "Céramique|gres": "Grès",
  "Céramique|terre cuite": "Terre cuite",
  "Céramique|email": "Émaux / émail",
  "Céramique|emaux": "Émaux / émail",
  "Céramique|emaillee": "Émaux / émail",
  "Céramique|emaillé": "Émaux / émail",
  "Céramique|barbotine": "Barbotine",
  "Céramique|autre": "Autre",
  "Verrerie|cristal": "Cristal",
  "Verrerie|opaline": "Opaline",
  "Verrerie|verre souffle": "Verre soufflé",
  "Verrerie|souffle": "Verre soufflé",
  "Verrerie|verre presse": "Verre pressé",
  "Verrerie|presse": "Verre pressé",
  "Verrerie|pate de verre": "Pâte de verre",
  "Verrerie|autre": "Autre",
  "Mobilier|siege": "Siège",
  "Mobilier|chaise": "Siège",
  "Mobilier|fauteuil": "Siège",
  "Mobilier|canape": "Siège",
  "Mobilier|table": "Table",
  "Mobilier|commode": "Commode",
  "Mobilier|armoire": "Armoire / buffet",
  "Mobilier|buffet": "Armoire / buffet",
  "Mobilier|secretaire": "Secrétaire / bureau",
  "Mobilier|bureau": "Secrétaire / bureau",
  "Mobilier|lit": "Lit",
  "Mobilier|miroir": "Miroir / psyché",
  "Mobilier|psyche": "Miroir / psyché",
  "Mobilier|autre": "Autre",
  "Montre / horlogerie|montre bracelet": "Montre bracelet",
  "Montre / horlogerie|montre-bracelet": "Montre bracelet",
  "Montre / horlogerie|gousset": "Montre gousset",
  "Montre / horlogerie|montre gousset": "Montre gousset",
  "Montre / horlogerie|pendule": "Pendule",
  "Montre / horlogerie|cartel": "Horloge de table / cartel",
  "Montre / horlogerie|horloge de table": "Horloge de table / cartel",
  "Montre / horlogerie|comtoise": "Comtoise",
  "Montre / horlogerie|reveil": "Réveil",
  "Montre / horlogerie|autre": "Autre",
  "Bijou|bague": "Bague",
  "Bijou|collier": "Collier",
  "Bijou|broche": "Broche",
  "Bijou|bracelet": "Bracelet",
  "Bijou|boucles d'oreilles": "Boucles d'oreilles",
  "Bijou|boucle d'oreille": "Boucles d'oreilles",
  "Bijou|parure": "Parure",
  "Bijou|autre": "Autre",
  "Argenterie / métal|argent massif": "Argent massif",
  "Argenterie / métal|argent": "Argent massif",
  "Argenterie / métal|metal argente": "Métal argenté",
  "Argenterie / métal|epns": "Métal argenté",
  "Argenterie / métal|plaque argent": "Métal argenté",
  "Argenterie / métal|etain": "Étain",
  "Argenterie / métal|cuivre": "Cuivre / laiton",
  "Argenterie / métal|laiton": "Cuivre / laiton",
  "Argenterie / métal|fer forge": "Fer forgé",
  "Argenterie / métal|bronze d'art": "Bronze d'art (objet)",
  "Argenterie / métal|bronze objet": "Bronze d'art (objet)",
  "Argenterie / métal|autre": "Autre",
  "Luminaire|lampe": "Lampe",
  "Luminaire|lustre": "Lustre",
  "Luminaire|applique": "Applique",
  "Luminaire|bougeoir": "Bougeoir / chandelier",
  "Luminaire|chandelier": "Bougeoir / chandelier",
  "Luminaire|lanterne": "Lanterne",
  "Luminaire|autre": "Autre",
  "Textile / tapisserie|tapisserie": "Tapisserie",
  "Textile / tapisserie|tapis": "Tapis",
  "Textile / tapisserie|broderie": "Broderie",
  "Textile / tapisserie|dentelle": "Dentelle",
  "Textile / tapisserie|costume": "Costume / tissu",
  "Textile / tapisserie|tissu ancien": "Costume / tissu",
  "Textile / tapisserie|autre": "Autre",
  "Livre / document|livre ancien": "Livre ancien",
  "Livre / document|livre": "Livre ancien",
  "Livre / document|manuscrit": "Manuscrit",
  "Livre / document|autographe": "Autographe",
  "Livre / document|carte": "Carte",
  "Livre / document|carte postale": "Carte",
  "Livre / document|carte geographique": "Carte",
  "Livre / document|affiche": "Affiche",
  "Livre / document|autre": "Autre",
  "Monnaie / médaille|monnaie": "Monnaie / pièce",
  "Monnaie / médaille|piece": "Monnaie / pièce",
  "Monnaie / médaille|medaille": "Médaille",
  "Monnaie / médaille|jeton": "Jeton",
  "Monnaie / médaille|decoration": "Décoration",
  "Monnaie / médaille|decoration militaire": "Décoration",
  "Monnaie / médaille|autre": "Autre",
  "Instrument|instrument a cordes": "Musique — cordes",
  "Instrument|violon": "Musique — cordes",
  "Instrument|guitare": "Musique — cordes",
  "Instrument|instrument a vent": "Musique — vent",
  "Instrument|flute": "Musique — vent",
  "Instrument|clarinette": "Musique — vent",
  "Instrument|piano": "Musique — clavier",
  "Instrument|clavier": "Musique — clavier",
  "Instrument|accordeon": "Musique — clavier",
  "Instrument|instrument scientifique": "Scientifique / optique",
  "Instrument|instrument d'optique": "Scientifique / optique",
  "Instrument|microscope": "Scientifique / optique",
  "Instrument|sextant": "Scientifique / optique",
  "Instrument|autre": "Autre",
  "Jouet|poupee": "Poupée",
  "Jouet|train": "Train / voiture",
  "Jouet|train electrique": "Train / voiture",
  "Jouet|voiture miniature": "Train / voiture",
  "Jouet|jeu": "Jeu",
  "Jouet|jeu de societe": "Jeu",
  "Jouet|ours": "Ours / peluche",
  "Jouet|peluche": "Ours / peluche",
  "Jouet|figurine": "Figurine / automate",
  "Jouet|automate": "Figurine / automate",
  "Jouet|autre": "Autre",
  "Curiosité|taxidermie": "Taxidermie / naturalia",
  "Curiosité|naturalia": "Taxidermie / naturalia",
  "Curiosité|mineral": "Minéral / fossile",
  "Curiosité|fossile": "Minéral / fossile",
  "Curiosité|ivoire": "Objet de cabinet ⚠️ CITES",
  "Curiosité|ecaille": "Objet de cabinet ⚠️ CITES",
  "Curiosité|corail": "Objet de cabinet ⚠️ CITES",
  "Curiosité|objet de cabinet": "Objet de cabinet ⚠️ CITES",
  "Curiosité|autre": "Autre",
  "Art asiatique|chine": "Chine",
  "Art asiatique|chinois": "Chine",
  "Art asiatique|japon": "Japon",
  "Art asiatique|japonais": "Japon",
  "Art asiatique|coree": "Corée",
  "Art asiatique|inde": "Inde / Asie du Sud-Est",
  "Art asiatique|asie du sud-est": "Inde / Asie du Sud-Est",
  "Art asiatique|autre": "Autre",
  "Art tribal|afrique": "Afrique",
  "Art tribal|africain": "Afrique",
  "Art tribal|oceanie": "Océanie",
  "Art tribal|amerindien": "Amérindien / précolombien",
  "Art tribal|precolombien": "Amérindien / précolombien",
  "Art tribal|autre": "Autre",
  "Autre|autre": "Autre / à identifier",
  "Autre|a identifier": "Autre / à identifier"
};
